version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shield-mongodb-hackathon"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pa8ajudgn2mh"
s3_prefix = "shield-mongodb-hackathon"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
